# SPDX-FileCopyrightText: © 2023-2024 Decompollaborate
# SPDX-License-Identifier: MIT

[package]
name = "ipl3checksum"
# Version should be synced with src/ipl3checksum/__init__.py, pyproject.toml and src/rs/version.rs
version = "1.3.0-dev0"
edition = "2021"
description = "Library to calculate the IPL3 checksum for N64 ROMs"
repository = "https://github.com/decompollaborate/ipl3checksum"
license = "MIT"
rust-version = "1.61.0"
categories = ["no-std", "no-std::no-alloc"]
keywords = ["n64", "metadata", "rom-header"]

[lib]
name = "ipl3checksum"
path = "src/rs/lib.rs"
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = ["std"]

alloc = []
std = ["alloc", "thiserror/std"]

c_bindings = ["alloc"]
python_bindings = ["dep:pyo3", "std"]

[dependencies]
md5 = "0.8"
thiserror = { version = "2", default-features = false }

pyo3 = { version="0.26", features = ["extension-module"], optional = true }
